HTML&CSS: Newsweek Clone project
brugobi/Newsweek-clone pull request #3
Opened 2020-05-07 22:10 UTC by brugobi

## Newsweek Clone project 

- the most import on this project is using bootstrap;
- It is responsive;

Thank you for the reviewer

2020-05-09 06:04 UTC, serdg0 commented
Hello @brugobi,
I had to mark this submission as invalid, because it doesn't show the lintering in the PR.

Feel free to message me in slack if anything comes up!.

2020-05-09 11:33 UTC, brugobi commented
Hello Sérgio, sorry about that I still learning
![Captura de Tela 2020-05-09 às 07 36 56](https://user-images.githubusercontent.com/44896500/81472623-55123f00-91c7-11ea-950c-b9cfc63456e6.png)
 , I forget to enable but now is ON

2020-05-09 11:39 UTC, brugobi commented
Hello Sérgio, sorry about that, I forget to enable but now is

2020-05-09 18:36 UTC, lucasmazo32 commented
# Project under review 🔭

2020-05-09 19:12 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

Before the projects get approved, there are some changes that you need to make. Mostly they are simple but improve an already great page.

### Happy coding! :computer:

## Lucas Mazo

2020-05-09 19:12 UTC, lucasmazo32 commented on assets/stylesheet/index.css
> +}
When you have multiple display nones with classes you can change it into maximum three display none. You can have one for each breakpoint and you won't have the need to create multiple classes. Kindly fix that.

2020-05-09 19:12 UTC, lucasmazo32 commented on index.html
> +                        <div class="col-lg opinion latest-news-mobile">
Kindly add the Signup for more newsletter field.

![image](https://user-images.githubusercontent.com/57414789/81482282-7bea6880-91fb-11ea-9c01-d506b292f167.png)

2020-05-09 19:12 UTC, lucasmazo32 commented on index.html
> +                        <div class="block-title"><a class="text-danger font-weight-bold" style="text-decoration: none;" href="/">CULTURE</a></div>
Kindly change this title to capitalize (Culture) instead of uppercase.

2020-05-09 19:12 UTC, lucasmazo32 commented on index.html
> +                        <div class="block-title"><a class="text-danger font-weight-bold" style="text-decoration: none;" href="/">SPORTS</a></div>
Kindly change this title to capitalize instead of uppercase.

2020-05-09 19:12 UTC, lucasmazo32 commented on index.html
> +                            </a>
This section on the Newsweek page stays the same in desktop and tablet. I will add the screenshot from tablet.

> Original
![image](https://user-images.githubusercontent.com/57414789/81482476-ef40aa00-91fc-11ea-9663-e97c188f492b.png)

> Your page
![image](https://user-images.githubusercontent.com/57414789/81482488-0b444b80-91fd-11ea-8259-4277419e70a4.png)

Kindly fix that

2020-05-09 19:12 UTC, lucasmazo32 commented on index.html
> +                                <img src="https://d.newsweek.com/en/full/1585087/may-08-15-2020-cover.jpg?w=170&amp;q=95&amp;f=c4d10af6474d34e586607b280b6589f0" class="card-img" alt="...">
This section uses two images in the original webpage. Kindly fix that. I will add a screenshot from the original page.

![image](https://user-images.githubusercontent.com/57414789/81482570-9e7d8100-91fd-11ea-90ed-5b2d4972036f.png)

2020-05-09 19:12 UTC, lucasmazo32 commented on index.html
> +                                    <a href="#" class="btn btn-danger">SIGN UP&nbsp;&nbsp;></a>
Please hide the image for the last section in the phone version.

> Your page
![image](https://user-images.githubusercontent.com/57414789/81482615-ff0cbe00-91fd-11ea-863d-06e9754957d1.png)

> Original 
![image](https://user-images.githubusercontent.com/57414789/81482631-10ee6100-91fe-11ea-95b2-f01cede1e443.png)

2020-05-09 19:12 UTC, lucasmazo32 commented on index.html
> +                            <i class="fa fa-linkedin" aria-hidden="true"></i>
Each of these icons should be enclosed by links (```<a href="#"><i ... </i></a>```). In the original webpage when you hover them, they change the colors. It's a nice detail that you can copy!

Also, in phone version, they are below the Newsweek logo.

> Original
![image](https://user-images.githubusercontent.com/57414789/81482699-9d008880-91fe-11ea-9d06-de381f6604c1.png)

> Your page
![image](https://user-images.githubusercontent.com/57414789/81482738-dcc77000-91fe-11ea-8abb-dd30ac98cc52.png)

2020-05-11 18:02 UTC, brugobi commented
thank you @lucasmazo32 for your review I really appreciate that and I  Kindly did all the recommendations

2020-05-11 21:49 UTC, jofer86 approved these changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All of the required changes were taken care off. This project looks great as it is. Great job!!

`status: Approved` :rocket: :rocket: :+1: :+1: 
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-05-11 22:30 UTC, merged